version: "3"

services:
  database:
    image: mongo:4.2

  users_api:
    build: users_api/
    ports:
      - "5500:5500"

  safe_api:
    build: safe_api/
    ports:
      - "5501:5501"

  token_dealer:
    build: token_dealer/
    ports:
      - "5502:5502"

  back_office:
    build: back_office/
    ports:
      - "5503:5503"