version: '3'
services:
  database:
    container_name: database
    image: mongo:4.2
    networks:
      - database-n

  users_api:
    container_name: users_api
    build: users_api/
    ports:
      - "5503:5503"
    volumes:
      - ./users_api/app:/app
    networks:
      - token_dealer-n
      - back_office-n
      - database-n

  safe_api:
    container_name: safe_api
    build: safe_api/
    ports:
      - "5501:5501"
    volumes:
      - ./safe_api/app:/app
    networks:
      - back_office-n
      - token_dealer-n

  token_dealer:
    container_name: token_dealer
    build: token_dealer/
    ports:
      - "5502:5502"
    volumes:
      - ./token_dealer/app:/app
    networks:
      - token_dealer-n

  back_office:
    container_name: back_office
    build: back_office/
    ports:
      - "5503:5503"
    volumes:
      - ./back_office/app:/app
    networks:
      - back_office-n

networks:
  back_office-n:
    driver: bridge
  token_dealer-n:
    driver: bridge
    internal: true
  database-n:
    driver: bridge
    internal: true