version: "3"

services:
  database:
    container_name: database
    image: mongo:4.2
    networks:
      - database-n

  users_api:
    container_name: users
    build: users_api/
    ports:
      - "5500:5500"
    networks:
      - frontend-n
      - token-n
      - database-n

  safe_api:
    container_name: safe
    build: safe_api/
    ports:
      - "5501:5501"
    networks:
      - frontend-n
      - token-n
      - database-n

  token_dealer:
    container_name: token
    build: token_dealer/
    ports:
      - "5502:5502"
    networks:
      - token-n

  back_office:
    container_name: frontend
    build: back_office/
    ports:
      - "5503:5503"
    networks:
      - frontend-n

networks:
  frontend-n:
    driver: bridge
  token-n:
    driver: bridge
    internal: true
  database-n:
    driver: bridge
    internal: true